# Generated by Django 3.2.9 on 2021-11-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offdatatest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offline_data',
            name='id_check',
            field=models.IntegerField(null=True),
        ),
    ]
